### ISSUE TITLE
Need a hint: window / one-sided

### ISSUE THREAD

**Issue by VictorEijkhout** [rabauke/mpl#10]
I'm failing to find any window / one-sided functions. I would guess that window is under communicator but I'm not finding it.

**Comment by rabauke** [comment]
One-sided communication has not yet been implemented. I never had a use case for this.

**Comment by VictorEijkhout** [comment]
Understood. I do hope you can find time for it. Judging by commits you are still working on MPL.

I find MPL a very elegant front-end to MPI, and C++ is an increasingly popular language in computational science. I'm working on an MPI (& OpenMP & PETSc) book and I've started incorporating MPL examples and explanations. It would be nice if I could advocate MPL as a complete MPI API in trainings that I do. 

https://web.corral.tacc.utexas.edu/CompEdu/pdf/pcse/

**Comment by VictorEijkhout** [comment]
Btw, windows are needed for MPI shared memory, and that is definitely a very useful thing.

**Comment by rabauke** [comment]
> https://web.corral.tacc.utexas.edu/CompEdu/pdf/pcse/

Nice and useful writeup. 

If time permits I will think about how to map MPI windows and one-sided communication API to a nice C++ API. This has, however, not highest priority for me. If one would aim to extend MPL to a feature complete replacement for MPI (what I do not), one would need to implement many other features as well: IO, process creation, etc.

**Comment by VictorEijkhout** [comment]
> one would need to implement many other features as well: IO

I/O was going to be my next question :-)
