### ISSUE TITLE
send a std::variant with isend/irecv

### ISSUE THREAD

**Issue by a-jp** [rabauke/mpl#12]
Hi,

Very new to your library, it's really nice.  For reference I only found out about it due to this thread I'm following:

[mpi-cxx-features](https://github.com/mpi-forum/mpi-issues/issues/288)

I'd like to send a std::variant.  At the moment I get: 
class mpl::struct_builder<std::variant<Class1, Class2> >' has no member named 'type'.

Both Class1 and Class2 have been added via the MPL_REFLECTION macro.  Before I debug, it occurred to me to check that it's possible to send a std::variant?

Thanks,
Andy

**Comment by a-jp** [comment]
I'll answer my own question...just realised your library is c++11 based and of course std::variant is c++17.  Any clues/suggestions as to how I might do this?

**Comment by rabauke** [comment]
I am afraid there is no way to send a union, a std::variant, a std::optional, or a std::any in a save and portable manner via MPI. Therefore, there will be (probably) no support for these types in MPL in the future.
