### ISSUE TITLE
MPI_Intercomm_create functionality

### ISSUE THREAD

**Issue by a-jp** [rabauke/mpl#22]
Hi,

Is `MPI_Intercomm_create` supported by your library? I couldn't see it.  Is it something that could be added? 

Is there a recommended way to do it if I've already used:

```
mpl::communicator group(mpl::communicator::split, comm_world, index);
```

How would I make the call to `MPI_Intercomm_create` using `group`?

Any help really appreciated,
Thanks,
Andy

**Comment by rabauke** [comment]
MPI inter-communicators are currently not supported. However, this is certainly a feature worth considering. 

Although MPI handles all communicators via the same kind of handle, MPL should model inter-communicators by a specific dedicated class, not via mpl::communicator. Thus, this will not be implemented just via a minimal modification of the mpl::communicator class.

One reason, why inter-communicators are not supported by MPL is just that I never had an actual use-case for this. I know the examples from the MPL standard, which are, however, rather academic. Can you please explain your use-case?

**Comment by a-jp** [comment]
@rabauke many thanks for the comments.  The use-case here is multiple program, multiple data (MPMD) style launch using: `mpirun -np X prog_1 : -np Y prog_2`.

In this case comm_world is of size X+Y.  Within comm_world two communicators are created:

```c++
mpl::communicator group0(mpl::communicator::split, comm_world, 0);
```
Here 0 is the application number, for prog_1, and group0 is of size X.  A second communicator is created as:

```c++
mpl::communicator group1(mpl::communicator::split, comm_world, 1);
```
Here 1 is the application number, for prog_2, and group1 is of size Y.  

The use-case is coupling two codes together that can be used to solve a complex multi-domain problem, that is otherwise not solvable via either individual code.  The coupling between the codes is achieved via MPI.  In this use-case it is essential to be able to communicate between group0 and group1, hence the need for `MPI_Intercomm_create`.

An older paper, as this is a well established approach, and very relevant reference for this use-case is below `[1]`.  This represents a real use-case and is representative of the type of problem that interests me; namely coupling two codes via MPI.

I hope you consider this for inclusion into your library, for present I will write a simple wrapper class around `MPI_Intercomm_create` type functions as I go.

Many thanks,

[[1]](https://ntrs.nasa.gov/api/citations/19970010711/downloads/19970010711.pdf)

**Comment by rabauke** [comment]
@a-jp Thanks for further details. I will consider inter-communicators as a future feature of MPL.

**Comment by a-jp** [comment]
ok thanks

**Comment by VictorEijkhout** [comment]
On , 2021Oct3, at 04:26, a-jp ***@***.******@***.***>> wrote:

In this use-case it is essential to be able to communicate between group0 and group1, hence the need for MPI_Intercomm_create.

I understand what you’re doing. But because your group0 & 1 come from splitting com_world you still have comm_world as a means of communication. Why is the inter communicator a better mechanism?

Other usage scenario: an inter communicator is created from MPI_Comm_spawn. I have a user who does this spawning but I can’t give you the details. However, I must say that this is a very rare case.

Victor.
