### ISSUE TITLE
Obtain raw MPI_Comm from mpl::communicator

### ISSUE THREAD

**Issue by a-jp** [rabauke/mpl#23]
In reference to #22 I am trying to use the raw c-api from MPI:

```c++
int MPI_Intercomm_create(MPI_Comm local_comm, int local_leader,
                         MPI_Comm peer_comm, int remote_leader, int tag, MPI_Comm * newintercomm)
```

How can I obtain the raw MPI communicator for comm_world, and the raw MPI communicator from my group, if the group was constructed from:

```c++
mpl::communicator group(mpl::communicator::split, comm_world, index);
```

where comm_world is an mpl type.  I need these raw MPI variables for local_comm and peer_comm.  I suppose I'm asking is there a function:

```c++
MPI_Comm mpl::communicator::GetRawMPIComm()
{
    return comm_;
}
```

Within the same code base how can I interact with the MPI library such as using MPI_Intercomm_create (see #22 for reasons why) and the MPL library if I need to get access to the underlying MPI "types/variables" from MPL?

Any help and or advice welcome (and work arounds as I need to get this working).

Many thanks,

**Comment by a-jp** [comment]
Just to see if it would work (not suggesting you'd adopt this addition or in this way): I did the following on the current master:

```bash
diff --git a/mpl/comm_group.hpp b/mpl/comm_group.hpp
index a01fd30..66f9958 100644
--- a/mpl/comm_group.hpp
+++ b/mpl/comm_group.hpp
@@ -280,6 +280,14 @@ namespace mpl {
     MPI_Comm comm_{MPI_COMM_NULL};
 
   public:
+
+    /// \brief Obtain access to underlying mpi communicator
+    /// \return raw MPI_Comm communicator
+    MPI_Comm get_mpi_comm() const
+    {
+        return comm_;
+    }
+
     /// \brief Equality types for communicator comparison.
     enum class equality_type {
       /// communicators are identical, i.e., communicators represent the same communication
```

This works perfectly for my needs.  I can then use this like:

```c++
MPI_Intercomm_create(groupcomm.get_mpi_comm(), 0, comm_world.get_mpi_comm(), rl, tag, &intercomm);
```
Am I doing anything silly here? Are there any mistakes to watch for with regards to the way your library works?

Thanks,

**Comment by a-jp** [comment]
Ok, I understand this from your perspective and the points you raised. I certainly use the library due to a number of the points you raised and they are positive. 

I guess you can see from my perspective and anyone else in the same boat, via the concrete example and use-case that I'm working through right now, that unless MPL implements every mpi function then this will keep coming up; co-existence of mpi and MPL within the same code base will be tricky. 

If you do implement the inter-comm api then this goes away for me, until then i guess I need to retain a local fork. 

I was really pleased to see the version contribution to spack.  Again, not that straightforward I guess if I'm maintaining a local unversioned fork due to the above requirements. 

Many thanks

**Comment by VictorEijkhout** [comment]
On , 2021Oct8, at 13:53, Heiko Bauke ***@***.******@***.***>> wrote:

Therefore, you must never call MPI_Comm_free on a handle that was returned by get_mpi_comm and you must never use this handle after the MPL communicator of which you called  get_mpi_comm went out of scope.

First thought: so return the communicator as a const ref. Second thought: that runs into the fact that there are a  ton of functions that add MPI_Info and what not to a communicator.

So how about returning

MPI_Comm const *MPL_Communicator::Get_comm();

(Hope I get that right: pointer that can not be re-pointed, to an object that can be altered.)

Would that be enough to return a communicator?

At some point in the past I also wanted the bare MPI communicator, but I can’t remember what the scenario was.

Victor.
