### ISSUE TITLE
Support for C++20 ranges

### ISSUE THREAD

**Issue by mlund** [rabauke/mpl#26]
It would be convenient to be able to transmit `std::ranges` view (C++20), e.g. a filtered or transformed sequence. I think there's a current limitation when passing iterators in that `begin()` and `end()` must be of the same type. This is usually not the case for ranges. Until C++20 I use `range-v3` but currently need to copy into a STL vector before mpi communication, see here:

https://github.com/mlund/faunus/blob/00ab258465bf09c02593fa66d85a405fc07b2a19/src/move.cpp#L391

(Update: I realise that the example code is not representative as the buffer is here replaced)

**Comment by rabauke** [comment]
Thanks for suggestion. I would like to point out that allowing begin and end iterators of different types will not suffice to support ranges. Ranges support is probably not so easy to implement.

The ranges library implements lazy evaluation. The underlying MPI, however, is not compatible with lazy evaluation. In particular, when `views::transform` is involved the range must be evaluated, e.g., by `ranges::to_vector`, before the data can be sent. In some situations, evaluating the range might be a unnecessary and lead to avoidable performance degradations. Furthermore, the usage of the ranges library involves typically anonymous temporary objects, which imposes further challenges for non-blocking communication.

Also note that the MPL documentation warns that sending STL containers via iterators "_is a convenience method, which may have non-optimal performance characteristics. Use alternative overloads in performance critical code sections._"

Ranges support has no high priority for me. Nevertheless, it should be considered when C++21 compilers have become more widespread. Ranges support will certainly _not_ rely on an iterator interface. It should be possible to pass a range directly as, for example, in `std::ranges::sort`.

**Comment by mlund** [comment]
Thanks for the feedback. Yes, I understand the woes of sending non-contiguous objects and hopefully the explicit conversion to STL containers will make it into C++23.
