### ISSUE TITLE
"on ramp" for legacy code and interop

### ISSUE THREAD

**Issue by jacobmerson** [rabauke/mpl#28]
@rabauke thanks for writing a great library. I'd like to make use of it in some of my projects, but I face the issue that I have legacy code that expect `MPI_Comm` to be passed around and make use of other third party C libraries that expect the same. In some sense there is no "on ramp" for me to use to convert my code to mpl.

Based on my understanding of the discussion [here](https://github.com/rabauke/mpl/issues/23) and [here](https://github.com/rabauke/mpl/issues/24) you have concerns about the user getting access to the raw `MPI_Comm` object for two reasons:

1. Ownership may be unclear
2. You don't want to enable mixing of MPI/MPL code because you would like MPL to be a complete self contained ecosystem

Although I understand the sentiment I would like make the following comments on those two points and ask you to reconsider extracting the raw `MPI_Comm` handle.

In terms of ownership, `MPI_Comm` when extracted from MPL has pointer semantics. And in modern C++ people expect that a naked pointer means a non owning pointer. Because, if you intend to transfer ownership you will use a smart pointer. In the case of the communicator handle which isn't a pointer so it will not be `nullptr` but `MPI_COMM_NULL` returning a reference has clear semantics that most C++ programmers should not have trouble with around object lifetime and scope.

In terms of code mixing I understand that you want to maintain the cleanliness and purity of your library (probably partially why it is so nice). But, this makes mpl usage a bit of a walled garden that prevents me from slowly bringing it onboard to my C++ code, or interfacing with third party libraries over which I have no control.

I understand why you have chosen the current design and respect that. However, I wanted to bring up the issue again as I'm sick of  writing my own MPI wrappers...

**Comment by a-jp** [comment]
👍

**Comment by jacobmerson** [comment]
Thanks!

**Comment by a-jp** [comment]
Thank you
