### ISSUE TITLE
v0.2.0 doxygen latex fails

### ISSUE THREAD

**Issue by VictorEijkhout** [rabauke/mpl#32]
```
! LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.360 \end{DoxyTemplParams}
```

Error seems to be in inclusion of `classmpl_1_1impl_1_1base__communicator.tex`. If I comment out the offending block I get an error on the next `DoxyTemplParams`.

**Comment by rabauke** [comment]
Building documentation via Doxygen output and LaTeX is neither tested nor supported.  Since recently, Doxygen is only used to parse the sources and to create some XML output which is further processed by Breathe and Sphinx.
