### ISSUE TITLE
scatterv problem in comm_group.hpp

### ISSUE THREAD

**Issue by HSUAN221** [rabauke/mpl#34]
![image](https://user-images.githubusercontent.com/48273316/222100722-d804b706-2d27-4ec5-aa0e-ef726c98db91.png)

As shown in figure, i think in line 3066 should be as below one:
![image](https://user-images.githubusercontent.com/48273316/222101622-869dbf39-95c8-4f1d-838c-98d0ec879cdf.png)

Beside that, the major reason of unit test can pass is  line 3066 didn't use in below unit test.
![image](https://user-images.githubusercontent.com/48273316/222102691-3334d010-769d-4452-87b5-b3b1e086e3da.png)

**Comment by rabauke** [comment]
@HSUAN221 Thank for your bug report.
