### ISSUE TITLE
bug in sendrecv?

### ISSUE THREAD

**Issue by RaulPPelaez** [rabauke/mpl#5]
Some overloads in comm_group.hpp (the ones using iterators I think) such as this one:

https://github.com/rabauke/mpl/blob/c4c83cfcf1f970bc1af6e5ba2667b40ebd97730e/mpl/comm_group.hpp#L1028-L1041

Ignore the "source" argument and instead always pass dest twice to the underlying version.

Is this by design?
If so, could you give me some insight on why?

Thanks!

**Comment by rabauke** [comment]
No, this is not by design. This is a bug. Thanks for your bug report.

**Comment by rabauke** [comment]
Has been fixed.
